"""empty message

Revision ID: d5471807df25
Revises: 31a436182d28
Create Date: 2018-09-22 02:04:46.273717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd5471807df25'
down_revision = '31a436182d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('donated', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('groups', 'donated',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'donated',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_table('groupusers')
    # ### end Alembic commands ###
